@url = http://localhost/dataescolar
@cookie = PHPSESSID=vkvmigcrdct0vqechg94hssled

POST {{url}}/lapsos
Content-Type: application/json
Cookie: {{cookie}}

{
	"id_periodo": 4,
	"inicio": "1/1/2023",
	"fin": "4/4/2023",
	"nombre": "1er Lapso"
}
